deadlock1:
	g++ -g -o deadlock_single 1.dead_lock_single_thread.cc -lpthread

deadlock2:
	g++ -g -o deadlock_multi 2.dead_lock_multi_thread.cc -lpthread

clean:
	rm -rf deadlock_single
	rm -rf deadlock_multi